# Generated by Django 2.2.12 on 2020-06-01 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200529_2054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='test',
            new_name='hjgjh',
        ),
        migrations.RemoveField(
            model_name='customtext',
            name='emp',
        ),
        migrations.RemoveField(
            model_name='customtext',
            name='name',
        ),
        migrations.RemoveField(
            model_name='customtext',
            name='subpage',
        ),
        migrations.RemoveField(
            model_name='customtext',
            name='test',
        ),
    ]
